/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package productos;

import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arman
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    Conexion obj = new Conexion();

    public Interfaz() {

        initComponents();
        obj.conecta();
        setLocationRelativeTo(null);
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Cliente");
        model.addColumn("Nombre");
        model.addColumn("Dirección");
        model.addColumn("Télefono");
        model.addColumn("Correo electrónico");
        model.setRowCount(10);
        tablilla.setModel(model);

    }

    String nomtabla = "clientes", var1 = "idCliente", var2 = "nombre", var3 = "direccion", var4 = "telefono", var5 = "correo";
    String t1 = "ID Cliente", t2 = "Nombre", t3 = "Dirección", t4 = "Télefono", t5 = "Correo electrónico";

    public void llenar(String nomT, String ti1, String ti2, String ti3, String ti4, String ti5) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn(ti1);
        model.addColumn(ti2);
        model.addColumn(ti3);
        model.addColumn(ti4);
        model.addColumn(ti5);
        try {
            String buscar = "Select * from " + nomT;
            Statement stm = obj.con.createStatement();
            ResultSet rs = stm.executeQuery(buscar);
            while (rs.next()) {
                Object[] fila = new Object[5];
                for (int i = 0; i < 5; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);
            }
        } catch (SQLException error) {
            System.out.println("Error: " + error);
        }
        tablilla.setModel(model);
    }

    public void titulosTab(String ti1, String ti2, String ti3, String ti4, String ti5) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn(ti1);
        model.addColumn(ti2);
        model.addColumn(ti3);
        model.addColumn(ti4);
        model.addColumn(ti5);

        model.setRowCount(10);
        tablilla.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablilla = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        txtBusc = new javax.swing.JTextField();
        btnBusc = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Opciones = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor de registros");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clientes", "Proveedores", "Productos" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        tablilla.setAutoCreateRowSorter(true);
        tablilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "A", "B", "C", "D", "E"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablilla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablillaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablilla);

        jToggleButton1.setText("Mostrar registros");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        btnBusc.setText("Buscar");
        btnBusc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAgregar)
                                .addGap(9, 9, 9)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBusc, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBusc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(209, 611, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBusc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnAgregar))
                .addContainerGap())
        );

        Opciones.setText("Opciones");
        Opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionesActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Acerca de...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Opciones.add(jMenuItem2);

        jMenuItem1.setText("Volver al menú");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Opciones.add(jMenuItem1);

        jMenuBar1.add(Opciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        switch ((String) jComboBox1.getSelectedItem()) {
            case "Clientes":
                nomtabla = "clientes";
                var1 = "idCliente";
                var2 = "nombre";
                var3 = "direccion";
                var4 = "telefono";
                var5 = "correo";
                t1 = "ID cliente";
                t2 = "Nombre";
                t3 = "Dirección";
                t4 = "Telefono";
                t5 = "Correo";
                titulosTab(t1, t2, t3, t4, t5);
                jToggleButton1.setSelected(false);
                break;

            case "Proveedores":
                nomtabla = "proveedores";
                var1 = "idProveedor";
                var2 = "nombre";
                var3 = "direccion";
                var4 = "telefono";
                var5 = "correo";
                t1 = "ID proveedor";
                t2 = "Nombre";
                t3 = "Dirección";
                t4 = "Telefono";
                t5 = "Correo";
                titulosTab(t1, t2, t3, t4, t5);
                jToggleButton1.setSelected(false);
                break;

            case "Productos":
                nomtabla = "productos";
                var1 = "idProducto";
                var2 = "nombre";
                var3 = "descripcion";
                var4 = "cantidad";
                var5 = "precio";
                t1 = "ID producto";
                t2 = "Nombre";
                t3 = "Descripcion";
                t4 = "Cantidad";
                t5 = "Precio";
                titulosTab(t1, t2, t3, t4, t5);

                jToggleButton1.setSelected(false);
                break;
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void tablillaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablillaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tablillaKeyPressed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tablilla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna fila.");
            return;
        }

        int id = Integer.parseInt(this.tablilla.getValueAt(fila, 0).toString());
        try {
            PreparedStatement ps = obj.con.prepareStatement("DELETE FROM " + nomtabla + " WHERE " + var1 + " = ?");
            ps.setInt(1, id);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro eliminado.");

            titulosTab(t1, t2, t3, t4, t5);
            llenar(nomtabla, t1, t2, t3, t4, t5);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al eliminar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int fila = tablilla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna fila.");
            return;
        }

        int id = Integer.parseInt(this.tablilla.getValueAt(fila, 0).toString());
        String alexander1 = tablilla.getValueAt(fila, 1).toString();
        String alexander2 = tablilla.getValueAt(fila, 2).toString();
        String alexamder3 = tablilla.getValueAt(fila, 3).toString();
        String alexander4 = tablilla.getValueAt(fila, 4).toString();

        try {
            PreparedStatement ps = obj.con.prepareStatement("UPDATE " + nomtabla + " SET " + var2 + "=?, " + var3 + "=?, " + var4 + "=?, " + var5 + "=? WHERE " + var1 + "=?");

            ps.setString(1, alexander1);
            ps.setString(2, alexander2);
            ps.setString(3, alexamder3);
            ps.setString(4, alexander4);
            ps.setInt(5, id);

            int filas = ps.executeUpdate();
            llenar(nomtabla, t1, t2, t3, t4, t5);

            if (filas > 0) {
                JOptionPane.showMessageDialog(null, "Registro actualizado con éxito.");
            } else {
                JOptionPane.showMessageDialog(null, "El registro no se pudo actualizar.");
            }

            titulosTab(t1, t2, t3, t4, t5);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al actualizar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void OpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionesActionPerformed
        setVisible(false);
        Menu m = new Menu();
        m.setVisible(true);
    }//GEN-LAST:event_OpcionesActionPerformed

    private void btnBuscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscActionPerformed
        String busc = txtBusc.getText();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn(t1);
        model.addColumn(t2);
        model.addColumn(t3);
        model.addColumn(t4);
        model.addColumn(t5);
        try {
            String buscar = "Select * from " + nomtabla + " WHERE " + var1 + "=" + busc + ";";
            Statement stm = obj.con.createStatement();
            ResultSet rs = stm.executeQuery(buscar);
            while (rs.next()) {
                Object[] fila = new Object[5];
                for (int i = 0; i < 5; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);
            }
            
        }
        catch (SQLException error) {
            JOptionPane.showMessageDialog(null, "Introduce un valor válido.");
        }
        tablilla.setModel(model);
        
    }//GEN-LAST:event_btnBuscActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        JToggleButton btn = (JToggleButton) evt.getSource();
        if (btn.isSelected()) {
            llenar(nomtabla, t1, t2, t3, t4, t5);
        } else {
            titulosTab(t1, t2, t3, t4, t5);

        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Aplicación para interactuar con registros en Java usando NetBeans IDE 17 a través de una tabla.", "¡Gracias!", EXIT_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Menu menito = new Menu();
        menito.setVisible(true);
        dispose();
        setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String agregar = "INSERT INTO " + nomtabla + " (" + var1 + ", " + var2 + ", " + var3 + ", " + var4 + ", " + var5 + ") VALUES  (?,?,?,?,?)";
        try {
            PreparedStatement pst = obj.con.prepareStatement(agregar);
            for (int i = 0; i < tablilla.getRowCount(); i++) {
                String c1 = (String) tablilla.getValueAt(i, 0);
                String c2 = (String) tablilla.getValueAt(i, 1);
                String c3 = (String) tablilla.getValueAt(i, 2);
                String c4 = (String) tablilla.getValueAt(i, 3);
                String c5 = (String) tablilla.getValueAt(i, 4);

                pst.setString(1, c1);
                pst.setString(2, c2);
                pst.setString(3, c3);
                pst.setString(4, c4);
                pst.setString(5, c5);

                pst.executeUpdate();

            }
            JOptionPane.showMessageDialog(null, "Registro(s) agregado(s) con éxito.");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al agregar los registros.");
        }
        titulosTab(t1, t2, t3, t4, t5);
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Opciones;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBusc;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable tablilla;
    private javax.swing.JTextField txtBusc;
    // End of variables declaration//GEN-END:variables
}
