/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package productos;

/**
 *
 * @author arman
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.SQLException;

public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCrea = new javax.swing.JButton();
        btnCargarDatos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnCargarDatos1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mIGestReg = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú principal");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Crear base de datos");

        btnCrea.setText("Crear");
        btnCrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreaActionPerformed(evt);
            }
        });

        btnCargarDatos.setText("Cargar");
        btnCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarDatosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Cargar datos en la base de datos");

        btnCargarDatos1.setText("Borrar");
        btnCargarDatos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarDatos1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Borrar base de datos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCargarDatos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCargarDatos1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrea, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnCrea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnCargarDatos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnCargarDatos1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Opciones");

        mIGestReg.setText("Gestionar registros");
        mIGestReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mIGestRegActionPerformed(evt);
            }
        });
        jMenu1.add(mIGestReg);

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreaActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/", "root", "");
            Statement stmt = con.createStatement();
            stmt.execute("create database gestor_tienda");
            JOptionPane.showMessageDialog(null, "Base de datos creada exitosamente.");
        } catch (ClassNotFoundException error) {
            JOptionPane.showMessageDialog(null, "Error al conectar con la base de datos: " + error);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Base de datos ya existente.");
        }

        try {
            String clientes = "CREATE TABLE clientes("
                    + "idCliente INT PRIMARY KEY AUTO_INCREMENT,"
                    + "nombre VARCHAR(200) NOT NULL,"
                    + "direccion VARCHAR(200) NOT NULL,"
                    + "telefono VARCHAR(200) NOT NULL,"
                    + "correo VARCHAR(200) NOT NULL"
                    + ")";
            String proveedores = "CREATE TABLE proveedores("
                    + "idProveedor INT PRIMARY KEY AUTO_INCREMENT,"
                    + "nombre VARCHAR(200) NOT NULL,"
                    + "direccion VARCHAR(200) NOT NULL,"
                    + "telefono VARCHAR(200) NOT NULL,"
                    + "correo VARCHAR(200) NOT NULL"
                    + ")";
            String productos = "CREATE TABLE productos("
                    + "idProducto INT PRIMARY KEY AUTO_INCREMENT,"
                    + "nombre VARCHAR(200) NOT NULL,"
                    + "descripcion VARCHAR(200) NOT NULL,"
                    + "cantidad VARCHAR(200) NOT NULL,"
                    + "precio FLOAT NOT NULL"
                    + ")";

            Conexion obj = new Conexion();
            obj.conecta();
            Statement st;
            st = (Statement) obj.con.createStatement();
            st.executeUpdate(clientes);
            st.executeUpdate(productos);
            st.executeUpdate(proveedores);

        } catch (SQLException error) {

        }
    }//GEN-LAST:event_btnCreaActionPerformed

    private void mIGestRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mIGestRegActionPerformed
        setVisible(false);
        Interfaz ls = new Interfaz();
        ls.setVisible(true);
    }//GEN-LAST:event_mIGestRegActionPerformed

    private void btnCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarDatosActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/gestor_tienda", "root", "");
            Statement stmt = con.createStatement();

            String clientesdata = "INSERT INTO clientes (nombre, direccion, telefono, correo) VALUES "
                    + "('Tai Andrade', 'Zona Centro, Aquiles Serdán #341', '+52 618 814 1516', 'maquinadefuego69@yahoo.com'),"
                    + "('Oswaldo Corral', 'Calle Paseo de las flores, Col. Nuevo Oeste #352', '+52 618 682 1873', 'gatitos13@outlook.com'),"
                    + "('Aldo Mayorquin', 'El cerro', '+52 678 783 3952', 'brazode35@gmail.com'),"
                    + "('Oscar Torres', 'Rep. de Guatemala, Fracc. Frente frio #184', '+52 618 038 0429', 'profehabiatarea@hotmail.com'),"
                    + "('Noemi Mayorquin', 'El cerro', '+52 623 894 1942', 'senoritamisterio27@gmail.com')";

            String productosdata = "INSERT INTO productos (nombre, descripcion, cantidad, precio) VALUES "
                    + "('Tomate /KG', 'Tomate bola', '50', '100'),"
                    + "('Manzana/KG', 'Manzana roja', '30', '80'),"
                    + "('Leche 1L', 'Leche de toro', '40', '60'),"
                    + "('Naranja /KG', 'Naranja jugosa', '25', '70'),"
                    + "('Pera /KG', 'Pera verde', '20', '90'),"
                    + "('Uva /KG', 'Uva morada', '35', '120'),"
                    + "('Sandía /KG', 'Sandía grande', '15', '150'),"
                    + "('Melón /KG', 'Melón dulce', '20', '110'),"
                    + "('Papaya /KG', 'Papaya fresca', '25', '130'),"
                    + "('Piña /KG', 'Piña tropical', '30', '100')";

            String proveedoresdata = "INSERT INTO proveedores (nombre, direccion, telefono, correo) VALUES "
                    + "('Juan Huerta', 'Blvd. Felipe Pescador 1830 Ote. Col. Nueva Vizcaya. Durango, Dgo. México C.P. 34080.', '+52 618 452 1980', 'jalexander@itdurango.edu.mx'),"
                    + "('María Pérez', 'Calle Principal 123, Colonia Centro, Ciudad de México, México C.P. 10000.', '+52 55 1234 5678', 'mariapicosita1975@gmail.com'),"
                    + "('Manuel Martínez', 'Av. Revolución 456, Col. Juárez, Monterrey, Nuevo León, México C.P. 64000.', '+52 81 9876 5432', 'manuelangaspataguanga99@hotmail.com')";

            stmt.executeUpdate(clientesdata);
            stmt.executeUpdate(productosdata);
            stmt.executeUpdate(proveedoresdata);

            JOptionPane.showMessageDialog(null, "Registros cargados exitosamente.");

        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al conectar con la base de datos.");
        }
    }//GEN-LAST:event_btnCargarDatosActionPerformed

    private void btnCargarDatos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarDatos1ActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/gestor_tienda", "root", "");
            Statement stmt = con.createStatement();
            stmt.executeUpdate("drop database gestor_tienda");
            JOptionPane.showMessageDialog(null, "Base de datos eliminada exitosamente.");
        } catch (ClassNotFoundException error) {
            JOptionPane.showMessageDialog(null, "Error al conectar con la base de datos: " + error);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Base de datos inexistente.");
        }

    }//GEN-LAST:event_btnCargarDatos1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarDatos;
    private javax.swing.JButton btnCargarDatos1;
    private javax.swing.JButton btnCrea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mIGestReg;
    // End of variables declaration//GEN-END:variables
}
